name: typie
description: Typie mobile app
publish_to: none
version: 1.1.4

environment:
  sdk: ^3.8.0

dependencies:
  assorted_layout_widgets: ^11.0.0
  auto_route: ^10.0.1
  back_button_interceptor: ^8.0.4
  built_value: ^8.9.5
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  dio_http2_adapter: ^2.6.0
  envied: ^1.1.1
  ferry: ^0.16.1+2
  ferry_flutter: ^0.9.1-dev.4
  file_picker: ^10.1.9
  firebase_analytics: ^11.5.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.2.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  gql_code_builder_serializers: ^0.1.0
  gql_dio_link: ^1.0.1+1
  gql_error_link: ^1.0.0+1
  gql_exec: ^1.0.0+1
  gql_link: ^1.0.0+1
  gql_transform_link: ^1.0.0
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0+1
  injectable: ^2.5.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  json_annotation: ^4.9.0
  kakao_flutter_sdk_user: ^1.9.7+3
  logger: ^2.5.0
  luthor: ^0.6.1
  mime: ^2.0.0
  mixpanel_flutter: ^2.4.4
  naver_login_sdk: ^3.0.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.0+1
  pointer_interceptor: ^0.10.1+2
  sentry: ^9.0.0
  sentry_flutter: ^9.0.0
  share_plus: ^11.0.0
  sign_in_with_apple: ^7.0.1
  transparent_image: ^2.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web_socket: ^1.0.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  envied_generator: ^1.1.1
  ferry_generator: ^0.14.0-dev.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  freezed_lint: ^0.0.9
  hive_ce_generator: ^1.9.1
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  leancode_lint: ^17.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/brands/
  - assets/icons/
  - assets/logos/

  fonts:
    - family: LucideLightIcons
      fonts:
        - asset: assets/fonts/LucideLightIcons.ttf
    - family: LucideLabIcons
      fonts:
        - asset: assets/fonts/LucideLabIcons.ttf
    - family: TypieIcons
      fonts:
        - asset: assets/fonts/TypieIcons.ttf
    - family: Interop
      fonts:
        - asset: assets/fonts/Interop-Regular.otf
          weight: 400
        - asset: assets/fonts/Interop-Medium.otf
          weight: 500
        - asset: assets/fonts/Interop-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Interop-Bold.otf
          weight: 700
